_wandb:
    value:
        cli_version: 0.26.1
        e:
            q0y3qdz0mveqa32b3pqrsbj9crx38o3b:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    macModel: Mac16,8
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "5368709120"
                args:
                    - --experiment
                    - pmnist
                codePath: src/run.py
                codePathLocal: src/run.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "183790694400"
                email: metznerchristian97@gmail.com
                executable: /Users/cmetzner/miniconda3/envs/continual_growing/bin/python
                git:
                    commit: c0dc1b21762f19bb7f8faef261f6223d918380af
                    remote: git@github.com:cjm972/continual-growing.git
                host: MacBook-Pro-von-Christian.local
                memory:
                    total: "25769803776"
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/cmetzner/lalaland/continual_growing/src/run.py
                python: CPython 3.14.4
                root: /Users/cmetzner/lalaland/continual_growing
                startedAt: "2026-05-04T21:49:32.384198Z"
                writerId: q0y3qdz0mveqa32b3pqrsbj9crx38o3b
        m: []
        python_version: 3.14.4
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 1
                - 16
            "4": 3.14.4
            "5": 0.26.1
            "12": 0.26.1
            "13": darwin-arm64
arch:
    value: mlp
checkpoint:
    value: ../checkpoints/pmnist_grow
checkpoint_dir:
    value: ../checkpoints/
cl_mode:
    value: domain-incremental
data_path:
    value: ../data/
device:
    value: mps
epochs:
    value: 10
experiment:
    value: pmnist
growth_rate:
    value: 10
growth_saturation:
    value: 0.2
growth_threshold:
    value: 0.05
hidden_n:
    value: 64
layers:
    value: 1
lr_mu:
    value: 0.01
lr_sigma:
    value: 0.01
output:
    value: pmnist_grow
parameter:
    value: ""
pi:
    value: 0.25
resume:
    value: "no"
rho:
    value: -0.4327521295671885
samples:
    value: 10
sbatch:
    value: 64
seed:
    value: 0
sig1:
    value: -0
sig2:
    value: 11.512925464970229
sigma_init:
    value: 0.5
sigma_prior1:
    value: 1
sigma_prior2:
    value: 1e-05
static:
    value: false
sti:
    value: 0
train_mode:
    value: grow
wandb_mode:
    value: online
