_wandb:
    value:
        cli_version: 0.26.1
        e:
            mnn0f7bh05ujlb9v3hzw1n44203fapky:
                args:
                    - --experiment
                    - pmnist
                codePath: src/run.py
                codePathLocal: src/run.py
                email: metznerchristian97@gmail.com
                executable: /Users/cmetzner/miniconda3/envs/continual_growing/bin/python
                git:
                    commit: 850299cefa2b42cc16fef392bfe3407d31e0f86f
                    remote: git@github.com:SaynaEbrahimi/UCB.git
                host: MacBook-Pro-von-Christian.local
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/cmetzner/lalaland/UCB/src/run.py
                python: CPython 3.14.4
                root: /Users/cmetzner/lalaland/UCB
                startedAt: "2026-05-03T20:09:56.627792Z"
                writerId: mnn0f7bh05ujlb9v3hzw1n44203fapky
        m: []
        python_version: 3.14.4
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 1
                - 16
            "4": 3.14.4
            "5": 0.26.1
            "12": 0.26.1
            "13": darwin-arm64
approach:
    value: ucb
arch:
    value: mlp
checkpoint:
    value: ../checkpoints/pmnist_ucb
checkpoint_dir:
    value: ../checkpoints/
data_path:
    value: ../data/
device:
    value: mps
experiment:
    value: pmnist
lr:
    value: 0.01
nepochs:
    value: 1
nhid:
    value: 64
nlayers:
    value: 1
output:
    value: pmnist_ucb
parameter:
    value: ""
pi:
    value: 0.25
resume:
    value: "no"
rho:
    value: -3
samples:
    value: 10
sbatch:
    value: 64
seed:
    value: 0
sig1:
    value: 0
sig2:
    value: 6
sti:
    value: 0
wandb_mode:
    value: online
